root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ../tmp/ams-server.exe ./cmd/server"
bin = "../tmp/ams-server.exe"
full_bin = "../tmp/ams-server.exe"
include_dir = ["cmd", "internal", "migrations", "web"]
include_ext = ["go", "sql", "html"]
exclude_dir = ["tmp", "vendor"]
delay = 1000
stop_on_error = true
send_interrupt = true

[log]
time = true

[misc]
clean_on_exit = true
